@baseUrl=http://localhost:3000/api


###
GET {{baseUrl}}/latest
Content-Type: application/json

###
GET {{baseUrl}}/trending
Content-Type: application/json

###
GET {{baseUrl}}/search?q=kaisar
Content-Type: application/json

###
GET {{baseUrl}}/login
Content-Type: application/json
###
GET {{baseUrl}}/drama
Content-Type: application/json

###
GET {{baseUrl}}/drama/7597697149484157957
Content-Type: application/json

